- type: replace
  path: /resource_pools/name=vms/cloud_properties/mounts?/-
  value:
    type: bind
    source: /var/run/docker.sock
    target: /var/run/docker.sock # Place into location that's not bosh managed

- type: replace
  path: /instance_groups/name=bosh/properties/docker_cpi/docker/host
  value: unix:///var/run/docker.sock

- type: remove
  path: /instance_groups/name=bosh/properties/docker_cpi/docker/tls

- type: remove
  path: /cloud_provider/properties/docker_cpi/docker/tls

# - type: replace
#   path: /resource_pools/name=vms/cloud_properties/ports
#   value:
#   - 22:22/tcp
#   - 6868:6868/tcp
#   - 25555:25555/tcp
#   - 4222:4222/tcp
#   - 25250:25250/tcp
#   - 8443:8443/tcp
#   - 8080:8080/tcp
#   - 443:443/tcp
#   - 8844:8844/tcp
#   - 8200:8200/tcp

- type: replace
  path: /resource_pools/name=vms/cloud_properties/PortBindings?
  value:
    6868/tcp: [{ HostPort: "6868", HostIp: "0.0.0.0" }]
    22/tcp: [{ HostPort: "22", HostIp: "0.0.0.0" }]
    25555/tcp: [{ HostPort: "25555", HostIp: "0.0.0.0" }]
    4222/tcp: [{ HostPort: "4222", HostIp: "0.0.0.0" }]
    25250/tcp: [{ HostPort: "25250", HostIp: "0.0.0.0" }]
    8443/tcp: [{ HostPort: "8443", HostIp: "0.0.0.0" }]
    8080/tcp: [{ HostPort: "8080", HostIp: "0.0.0.0" }]
    443/tcp: [{ HostPort: "443", HostIp: "0.0.0.0" }]
    8844/tcp: [{ HostPort: "8844", HostIp: "0.0.0.0" }]
    8200/tcp: [{ HostPort: "8200", HostIp: "0.0.0.0" }]

- type: replace
  path: /cloud_provider/properties/docker_cpi/agent/mbus
  value: https://mbus:((mbus_bootstrap_password))@127.0.0.1:6868

- type: replace
  path: /instance_groups/name=bosh/networks/name=default/static_ips
  value:
  - ((static_ip))
